#############################################################################
# Makefile for building: XFB
# Generated by qmake (3.1) (Qt 5.15.1)
# Project:  XFB.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile XFB.pro -spec linux-g++
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_WEBKITWIDGETS_LIB -DQT_WEBKIT_LIB -DQT_DESIGNER_LIB -DQT_UIPLUGIN_LIB -DQT_WIDGETS_LIB -DQT_DATAVISUALIZATION_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/qt -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtDesigner -I/usr/include/qt/QtUiPlugin -I/usr/include/phonon4qt5 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtDataVisualization -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtSql -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = XFB1.0.0
DISTDIR = /home/fred/cpp/XFB/.tmp/XFB1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib
LIBS          = $(SUBLIBS) /usr/lib/libQt5Multimedia.so /usr/lib/libQt5WebKitWidgets.so /usr/lib/libQt5WebKit.so /usr/lib/libQt5Designer.so /usr/lib/libphonon4qt5.so /usr/lib/libQt5Widgets.so /usr/lib/libQt5DataVisualization.so /usr/lib/libQt5Gui.so /usr/lib/libQt5Network.so /usr/lib/libQt5Sql.so /usr/lib/libQt5Xml.so /usr/lib/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = player.cpp \
		main.cpp \
		add_music_single.cpp \
		add_full_dir.cpp \
		addgenre.cpp \
		addjingle.cpp \
		add_pub.cpp \
		optionsdialog.cpp \
		aboutus.cpp \
		youtubedownloader.cpp \
		add_program.cpp \
		audioinput.cpp \
		qaudiolevel.cpp qrc_tr.cpp \
		qrc_resources.cpp \
		moc_player.cpp \
		moc_add_music_single.cpp \
		moc_add_full_dir.cpp \
		moc_addgenre.cpp \
		moc_addjingle.cpp \
		moc_add_pub.cpp \
		moc_optionsdialog.cpp \
		moc_aboutus.cpp \
		moc_youtubedownloader.cpp \
		moc_add_program.cpp \
		moc_audioinput.cpp \
		moc_config.cpp \
		moc_qaudiolevel.cpp
OBJECTS       = player.o \
		main.o \
		add_music_single.o \
		add_full_dir.o \
		addgenre.o \
		addjingle.o \
		add_pub.o \
		optionsdialog.o \
		aboutus.o \
		youtubedownloader.o \
		add_program.o \
		audioinput.o \
		qaudiolevel.o \
		qrc_tr.o \
		qrc_resources.o \
		moc_player.o \
		moc_add_music_single.o \
		moc_add_full_dir.o \
		moc_addgenre.o \
		moc_addjingle.o \
		moc_add_pub.o \
		moc_optionsdialog.o \
		moc_aboutus.o \
		moc_youtubedownloader.o \
		moc_add_program.o \
		moc_audioinput.o \
		moc_config.o \
		moc_qaudiolevel.o
DIST          = setup.sh \
		/usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCddb.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KContacts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/designer_defines.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		XFB.pro player.h \
		add_music_single.h \
		add_full_dir.h \
		addgenre.h \
		addjingle.h \
		add_pub.h \
		optionsdialog.h \
		aboutus.h \
		youtubedownloader.h \
		add_program.h \
		audioinput.h \
		config.h \
		qaudiolevel.h player.cpp \
		main.cpp \
		add_music_single.cpp \
		add_full_dir.cpp \
		addgenre.cpp \
		addjingle.cpp \
		add_pub.cpp \
		optionsdialog.cpp \
		aboutus.cpp \
		youtubedownloader.cpp \
		add_program.cpp \
		audioinput.cpp \
		qaudiolevel.cpp
QMAKE_TARGET  = XFB
DESTDIR       = 
TARGET        = XFB


first: all
####### Build rules

XFB: ui_player.h ui_add_music_single.h ui_add_full_dir.h ui_addgenre.h ui_addjingle.h ui_add_pub.h ui_optionsdialog.h ui_aboutus.h ui_youtubedownloader.h ui_add_program.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: XFB.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCddb.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KContacts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/designer_defines.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		XFB.pro \
		tr.qrc \
		resources.qrc
	$(QMAKE) -o Makefile XFB.pro -spec linux-g++
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_Attica.pri:
/usr/lib/qt/mkspecs/modules/qt_Baloo.pri:
/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivities.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri:
/usr/lib/qt/mkspecs/modules/qt_KArchive.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuth.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/qt/mkspecs/modules/qt_KCddb.pri:
/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KContacts.pri:
/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KCrash.pri:
/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri:
/usr/lib/qt/mkspecs/modules/qt_KDESu.pri:
/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri:
/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri:
/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri:
/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri:
/usr/lib/qt/mkspecs/modules/qt_KHtml.pri:
/usr/lib/qt/mkspecs/modules/qt_KI18n.pri:
/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KJS.pri:
/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri:
/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/qt/mkspecs/modules/qt_KParts.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeople.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KPty.pri:
/usr/lib/qt/mkspecs/modules/qt_KRunner.pri:
/usr/lib/qt/mkspecs/modules/qt_KScreen.pri:
/usr/lib/qt/mkspecs/modules/qt_KService.pri:
/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri:
/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KWallet.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri:
/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri:
/usr/lib/qt/mkspecs/modules/qt_Prison.pri:
/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_Solid.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/toolchain.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources_functions.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/unix/opengl.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/designer_defines.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/qmake_use.prf:
/usr/lib/qt/mkspecs/features/file_copies.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
XFB.pro:
tr.qrc:
resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile XFB.pro -spec linux-g++

qmake_all: FORCE


all: Makefile XFB

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents tr.qrc resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents player.h add_music_single.h add_full_dir.h addgenre.h addjingle.h add_pub.h optionsdialog.h aboutus.h youtubedownloader.h add_program.h audioinput.h config.h qaudiolevel.h $(DISTDIR)/
	$(COPY_FILE) --parents player.cpp main.cpp add_music_single.cpp add_full_dir.cpp addgenre.cpp addjingle.cpp add_pub.cpp optionsdialog.cpp aboutus.cpp youtubedownloader.cpp add_program.cpp audioinput.cpp qaudiolevel.cpp $(DISTDIR)/
	$(COPY_FILE) --parents player.ui add_music_single.ui add_full_dir.ui addgenre.ui addjingle.ui add_pub.ui optionsdialog.ui aboutus.ui youtubedownloader.ui add_program.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_tr.cpp qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_tr.cpp qrc_resources.cpp
qrc_tr.cpp: tr.qrc \
		/usr/bin/rcc \
		frances.qm \
		portugues.qm
	/usr/bin/rcc -name tr tr.qrc -o qrc_tr.cpp

qrc_resources.cpp: resources.qrc \
		/usr/bin/rcc \
		48x48.png \
		images/novo\ logo_12_cfundo2_900.png \
		images/lp_player_p2.png \
		images/lp_player_p1.png \
		images/lp_anim1.gif \
		images/loading.gif \
		images/lp_player_p0.png \
		images/lp_player_p4.png \
		images/splash.png \
		images/lp_player_p3.png \
		icons/ic_speaker_light.png \
		icons/system-suspend.png \
		icons/ic_cast_light.png \
		icons/project-development-close-all.png \
		icons/tab-new-background.png \
		icons/gtk-info.png \
		icons/stock_media-prev.png \
		icons/view-pim-notes.png \
		icons/quickopen-function.png \
		icons/stock_properties.png \
		icons/system-switch-user.png \
		icons/format-line-spacing-normal.png \
		icons/ftv2doc.png \
		icons/media-seek-forward.png \
		icons/distribute-horizontal-center.png \
		icons/ic_menu_view.png \
		icons/go-previous-view-page.png \
		icons/page-zoom.png \
		icons/led_blue_on.png \
		icons/document-edit.png \
		icons/view-certificate-export.png \
		icons/games-highscores.png \
		icons/news-subscribe.png \
		icons/measure.png \
		icons/im-ban-kick-user.png \
		icons/mail-forwarded-replied.png \
		icons/stroke-join-miter.png \
		icons/office-chart-polar.png \
		icons/distribute-horizontal-right.png \
		icons/stock_save.png \
		icons/snap-node.png \
		icons/edit-select.png \
		icons/draw-brush.png \
		icons/format-list-ordered.png \
		icons/ic_menu_edit.png \
		icons/view-choose.png \
		icons/ic_cast_off_light.png \
		icons/gnome-searchtool.png \
		icons/search.png \
		icons/archive-extract.png \
		icons/Add-jingles.png \
		icons/gtk-leave-fullscreen.png \
		icons/view-media-artist.png \
		icons/ic_tv_light.png \
		icons/list-resource-add.png \
		icons/network-disconnect.png \
		icons/format-text-bold.png \
		icons/view-time-schedule-baselined.png \
		icons/mail-encrypted-part.png \
		icons/distribute-horizontal-equal.png \
		icons/mail-flag.png \
		icons/show-menu.png \
		icons/audio-cd-duplicate.png \
		icons/linux-logo.png \
		icons/insert-text.png \
		icons/distribute-vertical-bottom.png \
		icons/go-first.png \
		icons/go-jump-declaration.png \
		icons/help-donate.png \
		icons/view-close.png \
		icons/project-development-close.png \
		icons/align-horizontal-left.png \
		icons/edit-paste.png \
		icons/documentation.png \
		icons/player-eject.png \
		icons/jockey.png \
		icons/align-horizontal-center.png \
		icons/office-chart-ring.png \
		icons/view-history.png \
		icons/led_yellow_on.png \
		icons/stock_new-bcard.png \
		icons/games-difficult.png \
		icons/ic_menu_help.png \
		icons/document-close.png \
		icons/go-down-search.png \
		icons/go-jump.png \
		icons/quickopen-file.png \
		icons/edit-delete.png \
		icons/view-sort-descending.png \
		icons/go-last-view-page.png \
		icons/view-pim-tasks-pending.png \
		icons/go-previous-use.png \
		icons/insert-image.png \
		icons/uranus.png \
		icons/arrow-right-double.png \
		icons/edit-find-user.png \
		icons/system-shutdown.png \
		icons/go-bottom.png \
		icons/page-4sides.png \
		icons/bdwn.png \
		icons/add-event-icon.png \
		icons/ic_launcher_youtube.png \
		icons/4.png \
		icons/snap-intersection.png \
		icons/heart200.png \
		icons/tab-close.png \
		icons/text-frame-unlink.png \
		icons/view-task-add.png \
		icons/ic_menu_directions.png \
		icons/ic_cast_on_1_light.png \
		icons/ic_menu_camera.png \
		icons/lifes.png \
		icons/stock_bookmark.png \
		icons/network-connect.png \
		icons/go-jump-locationbar.png \
		icons/edit-clear-list.png \
		icons/format-stroke-color.png \
		icons/system-reboot.png \
		icons/edit-table-insert-column-right.png \
		icons/view-pim-summary.png \
		icons/format-text-strikethrough.png \
		icons/zoom-fit-width.png \
		icons/view-process-users.png \
		icons/gtk-media-previous-ltr.png \
		icons/view-file-columns.png \
		icons/footerfacebookicon.png \
		icons/mail-reply-sender.png \
		icons/ic_pause_dark.png \
		icons/format-font-size-more.png \
		icons/games-hint.png \
		icons/bookmark-toolbar.png \
		icons/kmix-master.png \
		icons/configure.png \
		icons/configure-toolbars.png \
		icons/preferences-activities.png \
		icons/document-preview.png \
		icons/games-achievements.png \
		icons/gtk-media-stop.png \
		icons/edit-find-replace.png \
		icons/ic_launcher_voicedial.png \
		icons/gtk-media-previous-rtl.png \
		icons/games-config-custom.png \
		icons/project-open.png \
		icons/format-justify-fill.png \
		icons/document-revert.png \
		icons/ic_menu_rotate.png \
		icons/stock_folder-properties.png \
		icons/mail-signed-fully.png \
		icons/kfm-home.png \
		icons/gajim.png \
		icons/edit-find.png \
		icons/im-user.png \
		icons/gtk-quit.png \
		icons/office-chart-scatter.png \
		icons/edit-clear-history.png \
		icons/ic_menu_camera_video_view.png \
		icons/roll.png \
		icons/view-certificate-sign.png \
		icons/BTM.png \
		icons/dialog-cancel.png \
		icons/run-build-clean.png \
		icons/stock_media-stop.png \
		icons/youtube.png \
		icons/align-vertical-top.png \
		icons/ic_menu_upload.png \
		icons/format-font-size-less.png \
		icons/ic_media_route_on_mono_dark.png \
		icons/snap-orthogonal.png \
		icons/go-first-view-page.png \
		icons/go-next.png \
		icons/gnome-sticky-notes-applet.png \
		icons/document-export.png \
		icons/debug-run.png \
		icons/document-open.png \
		icons/rating.png \
		icons/system-suspend-hibernate.png \
		icons/arrow-left.png \
		icons/document-open-remote.png \
		icons/draw-triangle2.png \
		icons/transform-shear-up.png \
		icons/draw-halfcircle4.png \
		icons/zoom-1-to-2.png \
		icons/draw-polygon.png \
		icons/media-playback-start.png \
		icons/application-exit.png \
		icons/mail-signed-part.png \
		icons/format-disconnect-node.png \
		icons/gtk-print.png \
		icons/led_green_off.png \
		icons/snap-guideline.png \
		icons/ic_media_play.png \
		icons/player_play.png \
		icons/go-last.png \
		icons/ic_menu_delete.png \
		icons/draw-donut.png \
		icons/resource-calendar-insert.png \
		icons/document-print.png \
		icons/irc-close-channel.png \
		icons/object-flip-vertical.png \
		icons/view-form.png \
		icons/view-calendar-week.png \
		icons/distribute-vertical-margin.png \
		icons/zoom-next.png \
		icons/xfsm-logout.png \
		icons/tools-rip-audio-cd.png \
		icons/story-editor.png \
		icons/format-justify-center.png \
		icons/open.png \
		icons/stroke-cap-butt.png \
		icons/mars.png \
		icons/ftv2folderopen.png \
		icons/games-config-tiles.png \
		icons/document-edit-decrypt.png \
		icons/view-barcode.png \
		icons/document-decrypt.png \
		icons/format-break-node.png \
		icons/facebook.png \
		icons/document-preview-archive.png \
		icons/games-config-options.png \
		icons/draw-polyline.png \
		icons/document-properties.png \
		icons/ic_audiotrack.png \
		icons/mail-forwarded.png \
		icons/meeting-attending.png \
		icons/mail-message-new.png \
		icons/tools-check-spelling.png \
		icons/mail-reply-list.png \
		icons/format-line-spacing-double.png \
		icons/view-pim-calendar.png \
		icons/window-close.png \
		icons/im-message-new.png \
		icons/view-calendar-day.png \
		icons/debug-step-into.png \
		icons/view-time-schedule-calculus.png \
		icons/address-book-new.png \
		icons/office-chart-line-percentage.png \
		icons/im-kick-user.png \
		icons/media-optical-data-new.png \
		icons/document-edit-encrypt.png \
		icons/mail-attachment.png \
		icons/zoom-out.png \
		icons/media-optical-video-new.png \
		icons/document-export-table.png \
		icons/document-encrypt.png \
		icons/archive-insert-directory.png \
		icons/stock_help-add-bookmark.png \
		icons/view-calendar-holiday.png \
		icons/view-calendar-tasks.png \
		icons/view-time-schedule-insert.png \
		icons/zoom-original.png \
		icons/format-text-underline.png \
		icons/format-justify-right.png \
		icons/resource-calendar-child-insert.png \
		icons/text-speak.png \
		icons/go-previous-view.png \
		icons/object-flip-horizontal.png \
		icons/go-up-search.png \
		icons/document-new.png \
		icons/draw-square-inverted-corners.png \
		icons/view-statistics.png \
		icons/office-chart-bar-percentage.png \
		icons/games-config-background.png \
		icons/view-preview.png \
		icons/align-vertical-bottom-out.png \
		icons/mail-send-receive.png \
		icons/object-order-lower.png \
		icons/mail-reply-all.png \
		icons/window-duplicate.png \
		icons/mail-encrypted-full.png \
		icons/rhythmbox.png \
		icons/go-previous.png \
		icons/distribute-vertical-center.png \
		icons/list-add.png \
		icons/twiter.png \
		icons/news-unsubscribe.png \
		icons/add-program.png \
		icons/tools-media-optical-burn-image.png \
		icons/led_red_off.png \
		icons/insert-button.png \
		icons/firefox.png \
		icons/dialog-ok.png \
		icons/bonobo-component-browser.png \
		icons/ic_menu_call.png \
		icons/gtk-save.png \
		icons/document-swap.png \
		icons/get-hot-new-stuff.png \
		icons/redhat-home.png \
		icons/documentinfo.png \
		icons/media-playback-stop.png \
		icons/xfce-system-lock.png \
		icons/edit-table-insert-row-under.png \
		icons/ogg3.png \
		icons/media-skip-backward.png \
		icons/stock_media-next.png \
		icons/edit-table-cell-merge.png \
		icons/3.png \
		icons/media-record.png \
		icons/ic_gps_not_saving_grey600_96dp.png \
		icons/octocat.png \
		icons/edit-table-insert-column-left.png \
		icons/view-list-text.png \
		icons/view-time-schedule-baselined-add.png \
		icons/mp3.png \
		icons/view-calendar.png \
		icons/view-media-visualization.png \
		icons/chronometer.png \
		icons/align-horizontal-right.png \
		icons/trash-empty.png \
		icons/view-certificate-server-configure.png \
		icons/gnome-status.png \
		icons/ic_close_dark.png \
		icons/format-connect-node.png \
		icons/distribute-vertical-y.png \
		icons/draw-star.png \
		icons/ic_bluetooth_white.png \
		icons/edit-image-face-show.png \
		icons/edit-find-mail.png \
		icons/gtk-execute.png \
		icons/edit-text-frame-update.png \
		icons/ic_menu_gallery.png \
		icons/office-chart-area-stacked.png \
		icons/distribute-vertical-top.png \
		icons/iso-image-burn.png \
		icons/ic_tv_dark.png \
		icons/office-chart-line.png \
		icons/media-seek-backward.png \
		icons/mercury.png \
		icons/debug-execute-to-cursor.png \
		icons/mail-encrypted.png \
		icons/debug-step-instruction.png \
		icons/gnome-stock-mail-new.png \
		icons/stroke-join-round.png \
		icons/tab-detach.png \
		icons/office-chart-bar.png \
		icons/mail-mark-notjunk.png \
		icons/document-save-all.png \
		icons/gtk-home.png \
		icons/transform-rotate.png \
		icons/view-resource-calendar.png \
		icons/office-chart-line-stacked.png \
		icons/format-text-subscript.png \
		icons/document-open-recent.png \
		icons/view-task.png \
		icons/im-user-away.png \
		icons/process-stop.png \
		icons/ic_menu_preferences.png \
		icons/ftv2folderclosed.png \
		icons/zoom-fit-best.png \
		icons/color-picker-grey.png \
		icons/edit-bomb.png \
		icons/ic_bluetooth_grey.png \
		icons/player_pause.png \
		icons/view-grid.png \
		icons/flag-black.png \
		icons/list-add-user.png \
		icons/edit-copy.png \
		icons/color-picker-black.png \
		icons/view-process-all.png \
		icons/ic_menu_shuffle.png \
		icons/view-task-child.png \
		icons/flag-red.png \
		icons/view-right-new.png \
		icons/view-form-action.png \
		icons/format-justify-left.png \
		icons/view-certificate-export-server.png \
		icons/arrow-down-double.png \
		icons/ic_audiotrack_light.png \
		icons/view-task-child-add.png \
		icons/ic_menu_mylocation.png \
		icons/transform-shear-left.png \
		icons/evolution-calendar.png \
		icons/edit-undo.png \
		icons/fileprint.png \
		icons/draw-triangle1.png \
		icons/view-calendar-special-occasion.png \
		icons/view-pim-contacts.png \
		icons/ftv2mlastnode.png \
		icons/object-rotate-right.png \
		icons/edit-table-delete-column.png \
		icons/draw-halfcircle3.png \
		icons/view-presentation.png \
		icons/milestone.png \
		icons/document-sign.png \
		icons/skype.png \
		icons/view-calendar-time-spent.png \
		icons/saturn.png \
		icons/stock_mail-send-receive.png \
		icons/ic_menu_zoom.png \
		icons/clear.png \
		icons/view-process-tree.png \
		icons/audio-cd-new.png \
		icons/ic_menu_archive.png \
		icons/run-build-prune.png \
		icons/player-volume.png \
		icons/im-user-busy.png \
		icons/ic_pause_light.png \
		icons/ic_media_pause.png \
		icons/media-eject.png \
		icons/arrow-left-double.png \
		icons/evince.png \
		icons/stock_file-properties.png \
		icons/ic_speaker_group_dark.png \
		icons/draw-path.png \
		icons/player_end.png \
		icons/im-invisible-user.png \
		icons/ftv2cl.png \
		icons/stock_text_justify.png \
		icons/ic_settings_black_24dp.png \
		icons/view-media-playlist.png \
		icons/configure-shortcuts.png \
		icons/page-simple.png \
		icons/format-text-direction-rtl.png \
		icons/view-list-tree.png \
		icons/irc-join-channel.png \
		icons/go-top.png \
		icons/view-media-equalizer.png \
		icons/tool-animator.png \
		icons/download-later.png \
		icons/mail-signed-full.png \
		icons/mail-forward.png \
		icons/object-group.png \
		icons/checkbox.png \
		icons/mail-tagged.png \
		icons/edit-clear-locationbar-rtl.png \
		icons/ogg-icon.png \
		icons/layer-visible-on.png \
		icons/arrow-right.png \
		icons/insert-table.png \
		icons/speaker.png \
		icons/mail-mark-unread.png \
		icons/document-open-folder.png \
		icons/view-fullscreen.png \
		icons/gtk-media-play-ltr.png \
		icons/ic_menu_mapmode.png \
		icons/gnome-run.png \
		icons/document-print-preview.png \
		icons/media-optical-audio-new.png \
		icons/edit-find-project.png \
		icons/ic_menu_save.png \
		icons/edit-table-insert-row-above.png \
		icons/edit-guides.png \
		icons/view-calendar-wedding-anniversary.png \
		icons/view-ldap-resource.png \
		icons/folder-new.png \
		icons/hardinfo.png \
		icons/format-line-spacing-triple.png \
		icons/irc-unvoice.png \
		icons/system-run.png \
		icons/filesave.png \
		icons/view-list-details.png \
		icons/mail-reply-custom.png \
		icons/view-calendar-timeline.png \
		icons/align-horizontal-left-out.png \
		icons/jupiter.png \
		icons/moon.png \
		icons/led_blue_off.png \
		icons/pdf-annotations.png \
		icons/distribute-horizontal-page.png \
		icons/im-user-offline.png \
		icons/meeting-attending-tentative.png \
		icons/edit-table-delete-row.png \
		icons/transform-crop.png \
		icons/flag-blue.png \
		icons/transform-scale.png \
		icons/youtubeicon.png \
		icons/edit-redo.png \
		icons/record.png \
		icons/ic_settings_googblue_24dp.png \
		icons/stock_print.png \
		icons/debug-step-over.png \
		icons/stroke-join-bevel.png \
		icons/flag-green.png \
		icons/svn-update.png \
		icons/footertwittericon.png \
		icons/ic_menu_back.png \
		icons/go-first-view.png \
		icons/arrow-down.png \
		icons/edit-clear.png \
		icons/tree.png \
		icons/resource-group.png \
		icons/stock_media-pause.png \
		icons/document-print-direct.png \
		icons/sound-juicer.png \
		icons/games-endturn.png \
		icons/media-skip-forward.png \
		icons/system-search.png \
		icons/games-solve.png \
		icons/lock.png \
		icons/view-time-schedule-baselined-remove.png \
		icons/mail-mark-unread-new.png \
		icons/view-restore.png \
		icons/ic_sysbar_quicksettings.png \
		icons/list-remove.png \
		icons/gnome-logout.png \
		icons/draw-arrow-forward.png \
		icons/view-sidetree.png \
		icons/ic_settings_grey600_24dp.png \
		icons/gtk-media-pause.png \
		icons/tab-new.png \
		icons/quickopen.png \
		icons/draw-arrow-back.png \
		icons/office-chart-polar-stacked.png \
		icons/view-financial-forecast.png \
		icons/view-right-close.png \
		icons/ic_menu_compass.png \
		icons/edit-link.png \
		icons/svn-commit.png \
		icons/stock-home.png \
		icons/ogg-b.png \
		icons/soundconverter.png \
		icons/6.png \
		icons/view-pim-tasks.png \
		icons/document-edit-decrypt-verify.png \
		icons/text-frame-link.png \
		icons/view-calendar-journal.png \
		icons/nautilus-actions.png \
		icons/draw-arrow-down.png \
		icons/page-2sides.png \
		icons/align-vertical-top-out.png \
		icons/zoom-draw.png \
		icons/view-calendar-birthday.png \
		icons/sync_off.png \
		icons/ic_menu_recent_history.png \
		icons/view-calendar-month.png \
		icons/view-pim-mail.png \
		icons/format-fill-color.png \
		icons/ic_menu_play_clip.png \
		icons/ic_menu_close_clear_cancel.png \
		icons/format-remove-node.png \
		icons/guayadeque.png \
		icons/distribute-horizontal-left.png \
		icons/ic_speaker_group_light.png \
		icons/ejecter.png \
		icons/bookmark-new.png \
		icons/flag-yellow.png \
		icons/insert-text-frame.png \
		icons/gnome-subtitles.png \
		icons/gnome-session.png \
		icons/mail-queue.png \
		icons/acrobat.png \
		icons/zoom-select.png \
		icons/edit-delete-shred.png \
		icons/view-calendar-upcoming-events.png \
		icons/draw-cross.png \
		icons/sun.png \
		icons/quickopen-class.png \
		icons/sync_on.png \
		icons/ic_cast_grey.png \
		icons/stock_mail-compose.png \
		icons/mplayer.png \
		icons/go-parent-folder.png \
		icons/draw-eraser.png \
		icons/office-chart-pie.png \
		icons/draw-ellipse.png \
		icons/run-build-install.png \
		icons/color-picker.png \
		icons/icon.png \
		icons/arrow-up.png \
		icons/preflight-verifier.png \
		icons/games-config-board.png \
		icons/tab-close-other.png \
		icons/gohome.png \
		icons/code-class.png \
		icons/format-list-unordered.png \
		icons/player_start.png \
		icons/help-hint.png \
		icons/tools-media-optical-format.png \
		icons/format-indent-more.png \
		icons/view-split-top-bottom.png \
		icons/artsfftscope.png \
		icons/draw-spiral.png \
		icons/character-set.png \
		icons/go-jump-definition.png \
		icons/edit-select-all.png \
		icons/debug-step-out.png \
		icons/mail-signed-verified.png \
		icons/ic_menu_send.png \
		icons/player_stop.png \
		icons/tools-rip-video-dvd.png \
		icons/gtk-justify-fill.png \
		icons/zoom-2-to-1.png \
		icons/stroke-cap-square.png \
		icons/edit-node.png \
		icons/draw-halfcircle2.png \
		icons/format-add-node.png \
		icons/stock_attach.png \
		icons/gtk-open.png \
		icons/meeting-participant-request-response.png \
		icons/ic_cast_dark.png \
		icons/meeting-participant-no-response.png \
		icons/ic_menu_attachment.png \
		icons/tools-rip-video-cd.png \
		icons/draw-triangle4.png \
		icons/bookmarks-organize.png \
		icons/view-web-browser-dom-tree.png \
		icons/stock_media-play.png \
		icons/insert-horizontal-rule.png \
		icons/zoom-previous.png \
		icons/list-remove-user.png \
		icons/mail-receive.png \
		icons/document-import.png \
		icons/venus.png \
		icons/help-contextual.png \
		icons/stock_new-address-book.png \
		icons/view-time-schedule-edit.png \
		icons/view-left-close.png \
		icons/ic_media_route_disabled_mono_dark.png \
		icons/gtk-media-next-ltr.png \
		icons/code-context.png \
		icons/transform-crop-and-resize.png \
		icons/googlemusicframe.png \
		icons/format-indent-less.png \
		icons/mail-message-new-list.png \
		icons/go-previous-context.png \
		icons/mail-meeting-request-reply.png \
		icons/go-next-use.png \
		icons/ic_menu_more.png \
		icons/xfce-system-exit.png \
		icons/app-ogg.png \
		icons/ic_launcher.png \
		icons/object-order-front.png \
		icons/edit-delete-page.png \
		icons/rec.png \
		icons/fork.png \
		icons/ic_media_route_on_0_mono_dark.png \
		icons/ic_cast_white.png \
		icons/media-optical-burn.png \
		icons/mail-replied.png \
		icons/go-up.png \
		icons/draw-triangle.png \
		icons/select-rectangular.png \
		icons/run-build-configure.png \
		icons/view-sort-ascending.png \
		icons/gtk-media-next-rtl.png \
		icons/zoom-in.png \
		icons/irc-voice.png \
		icons/edit-table-cell-split.png \
		icons/ic_play_light.png \
		icons/object-order-raise.png \
		icons/ic_menu_goto.png \
		icons/palimpsest.png \
		icons/mail-mark-important.png \
		icons/align-vertical-center.png \
		icons/contact-new.png \
		icons/view-refresh.png \
		icons/go-next-view-page.png \
		icons/project-development-new-template.png \
		icons/document-edit-sign-encrypt.png \
		icons/ic_menu_share.png \
		icons/kfind.png \
		icons/draw-arrow-up.png \
		icons/document-save-as.png \
		icons/layer-visible-off.png \
		icons/edit-table-insert-row-below.png \
		icons/edit-image-face-detect.png \
		icons/run-build-file.png \
		icons/tools-media-optical-burn.png \
		icons/user-group-properties.png \
		icons/earth.png \
		icons/help-feedback.png \
		icons/view-form-table.png \
		icons/gtk-refresh.png \
		icons/system-log-out.png \
		icons/format-text-superscript.png \
		icons/view-multiple-objects.png \
		icons/zoom-fit-height.png \
		icons/distribute-horizontal-x.png \
		icons/format-text-direction-ltr.png \
		icons/go-last-view.png \
		icons/ic_menu_refresh.png \
		icons/window-new.png \
		icons/view-media-lyrics.png \
		icons/flag.png \
		icons/mail-signature-unknown.png \
		icons/archive-insert.png \
		icons/desktop-effects.png \
		icons/view-time-schedule-child-insert.png \
		icons/ic_play_dark.png \
		icons/reload_page.png \
		icons/view-calendar-agenda.png \
		icons/format-text-italic.png \
		icons/edit-clear-locationbar-ltr.png \
		icons/stroke-cap-round.png \
		icons/view-process-all-tree.png \
		icons/align-vertical-bottom.png \
		icons/edit-image-face-recognize.png \
		icons/help-contents.png \
		icons/transform-shear-down.png \
		icons/mail-mark-read.png \
		icons/ic_voice_search_api_holo_light.png \
		icons/download.png \
		icons/view-certificate.png \
		icons/code-block.png \
		icons/games-config-theme.png \
		icons/ic_close_light.png \
		icons/irc-remove-operator.png \
		icons/im-ban-user.png \
		icons/folder-sync.png \
		icons/resource-group-new.png \
		icons/view-barcode-add.png \
		icons/object-ungroup.png \
		icons/view-pim-news.png \
		icons/document-save.png \
		icons/tools-media-optical-erase.png \
		icons/media-optical-copy.png \
		icons/goa-account-facebook.png \
		icons/debug-step-into-instruction.png \
		icons/view-list-icons.png \
		icons/code-typedef.png \
		icons/resource-calendar-child.png \
		icons/gnome-settings-default-applications.png \
		icons/document-edit-sign.png \
		icons/1.png \
		icons/gmusicbrowser.png \
		icons/view-certificate-add.png \
		icons/go-down.png \
		icons/transform-shear-right.png \
		icons/mail-mark-junk.png \
		icons/object-rotate-left.png \
		icons/mp3b.png \
		icons/view-certificate-import.png \
		icons/stock_leave-fullscreen.png \
		icons/5.png \
		icons/ic_cast_on_light.png \
		icons/page-3sides.png \
		icons/player-time.png \
		icons/dialog-ok-apply.png \
		icons/ic_menu_forward.png \
		icons/gnome-calendar.png \
		icons/bookmark-new-list.png \
		icons/go-jump-today.png \
		icons/document-edit-verify.png \
		icons/draw-circle.png \
		icons/view-calendar-whatsnext.png \
		icons/ic_media_route_on_2_mono_dark.png \
		icons/go-home.png \
		icons/system-lock-screen.png \
		icons/ic_menu_mark.png \
		icons/success.png \
		icons/ic_menu_info_details.png \
		icons/view-pim-journal.png \
		icons/view-process-system.png \
		icons/draw-text.png \
		icons/project-development.png \
		icons/feed-subscribe.png \
		icons/pithos.png \
		icons/view-calendar-workweek.png \
		icons/user-group-delete.png \
		icons/led_red_on.png \
		icons/format-text-color.png \
		icons/tools-media-optical-copy.png \
		icons/go-next-context.png \
		icons/mail-invitation.png \
		icons/ic_menu_search.png \
		icons/mail-reply-custom-all.png \
		icons/office-chart-area.png \
		icons/ic_media_route_off_mono_dark.png \
		icons/run-build.png \
		icons/run-build-install-root.png \
		icons/fileopen.png \
		icons/icon48x48.png \
		icons/mail-signed.png \
		icons/ic_menu_favorite.png \
		icons/draw-freehand.png \
		icons/view-bank.png \
		icons/distribute-vertical-equal.png \
		icons/fill-color.png \
		icons/guake.png \
		icons/view-conversation-balloon.png \
		icons/format-join-node.png \
		icons/object-order-back.png \
		icons/view-split-left-right.png \
		icons/neptune.png \
		icons/office-chart-area-precentage.png \
		icons/code-variable.png \
		icons/distribute-horizontal-margin.png \
		icons/ic_cast_disabled_light.png \
		icons/user-properties.png \
		icons/view-filter.png \
		icons/irc-operator.png \
		icons/list-add-font.png \
		icons/gnome-lockscreen.png \
		icons/snap-extension.png \
		icons/view-object-histogram-linear.png \
		icons/document-print-frame.png \
		icons/led_green_on.png \
		icons/arrow-up-double.png \
		icons/ic_cast_on_0_light.png \
		icons/ic_menu_home.png \
		icons/ic_gps_saving_grey600_96dp.png \
		icons/text-field.png \
		icons/view-certificate-export-secret.png \
		icons/view-calendar-list.png \
		icons/remove_element.png \
		icons/view-calendar-upcoming-days.png \
		icons/edit-image-face-add.png \
		icons/debug-run-cursor.png \
		icons/transform-move.png \
		icons/dashboard-show.png \
		icons/draw-line.png \
		icons/code-function.png \
		icons/draw-halfcircle1.png \
		icons/debug-execute-from-cursor.png \
		icons/draw-bezier-curves.png \
		icons/minitunes.png \
		icons/ic_settings_white_24dp.png \
		icons/draw-triangle3.png \
		icons/media-playback-pause.png \
		icons/nexuiz.png \
		icons/edit-rename.png \
		icons/brasero.png \
		icons/dialog-close.png \
		icons/tab-duplicate.png \
		icons/user-group-new.png \
		icons/appointment-new.png \
		icons/go-next-view.png \
		icons/mail-send.png \
		icons/gtk-properties.png \
		icons/ic_cast_on_2_light.png \
		icons/view-time-schedule.png \
		icons/distribute-vertical-page.png \
		icons/ftv2pnode.png \
		icons/ic_media_route_on_1_mono_dark.png \
		icons/office-chart-bar-stacked.png \
		icons/document-open-data.png \
		icons/insert-link.png \
		icons/exit.png \
		icons/youtobe.png \
		icons/color-picker-white.png \
		icons/ic_speaker_dark.png \
		icons/archive-remove.png \
		icons/view-process-own.png \
		icons/edit-cut.png \
		icons/view-object-histogram-logarithmic.png \
		icons/led_yellow_off.png \
		icons/ic_menu_add.png \
		icons/align-horizontal-right-out.png \
		icons/draw-rectangle.png \
		icons/flat/Duck-32.png \
		icons/flat/Firewall-48.png \
		icons/flat/Playlist-48.png \
		icons/flat/Audio\ Wave-48.png \
		icons/flat/Data\ Pending-48.png \
		icons/flat/Record-32.png \
		icons/flat/Harp-48.png \
		icons/flat/Toggle\ On-48.png \
		icons/flat/Start\ Menu-48.png \
		icons/flat/Stop\ Sign-32.png \
		icons/flat/Natural\ User\ Interface\ 2-48.png \
		icons/flat/Open\ Source-32.png \
		icons/flat/HDD-48.png \
		icons/flat/Open\ Folder-32.png \
		icons/flat/Einstein-48.png \
		icons/flat/Maintenance-48.png \
		icons/flat/Shuffle-48.png \
		icons/flat/Upload\ to\ Cloud-48.png \
		icons/flat/Quick\ Mode\ On-48.png \
		icons/flat/Chicken-32.png \
		icons/flat/Telescope-48.png \
		icons/flat/Security\ Checked-48.png \
		icons/flat/Cloud-48.png \
		icons/flat/Data\ Arrived-48.png \
		icons/flat/Music\ Transcript-48.png \
		icons/flat/Treble\ Clef-48.png \
		icons/flat/Slave-48.png \
		icons/flat/Microphone-48.png \
		icons/flat/Clown\ Fish-32.png \
		icons/flat/Fast\ Forward-32(1).png \
		icons/flat/Connection\ Sync-48.png \
		icons/flat/Import-48.png \
		icons/flat/Fast\ Forward-32.png \
		icons/flat/Violin-48.png \
		icons/flat/Delete\ Slide-32.png \
		icons/flat/Registry\ Editor-48.png \
		icons/flat/Quick\ Mode\ Off-48.png \
		icons/flat/Butterfly-32.png \
		icons/flat/Micro\ SD-48.png \
		icons/flat/Cat-32.png \
		icons/flat/New\ Slide-32.png \
		icons/flat/CD-48.png \
		icons/flat/Audio\ Wave\ 2-48.png \
		icons/flat/Toggle\ Off-48.png \
		icons/flat/Alto\ Saxophone-52.png \
		icons/flat/Connection\ Sync-32.png \
		icons/flat/Slide\ Layout-32.png \
		icons/flat/Stop-32.png \
		icons/flat/Dolphin-32.png \
		icons/flat/Potted\ Plant-32.png \
		icons/flat/Radio-48.png \
		icons/flat/Cloud\ Storage-48.png \
		icons/flat/Next-32.png \
		icons/flat/Save-48.png \
		icons/flat/Remote\ Working-48.png \
		icons/flat/Vertical\ Settings\ Mixer-32.png \
		icons/flat/Download\ From\ Cloud-48.png \
		icons/flat/SSD-48.png \
		icons/flat/Console-48.png \
		icons/flat/Bumblebee-32.png \
		icons/flat/Pause-32.png \
		icons/flat/Export-48.png \
		icons/flat/Delete\ Shield-48.png \
		icons/flat/Cloud\ Checked-48.png \
		icons/flat/Air\ Play-48.png \
		icons/flat/Music\ Conductor-48.png \
		icons/flat/Restriction\ Shield-48.png \
		icons/flat/Play-64.png \
		icons/flat/Tasks-48.png \
		icons/flat/Database-48.png \
		icons/flat/Previous-32.png \
		icons/flat/Lyre-32.png \
		icons/flat/Headphones-48.png \
		icons/flat/Rice\ Bowl\ Filled-32.png
	/usr/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/qt/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_player.cpp moc_add_music_single.cpp moc_add_full_dir.cpp moc_addgenre.cpp moc_addjingle.cpp moc_add_pub.cpp moc_optionsdialog.cpp moc_aboutus.cpp moc_youtubedownloader.cpp moc_add_program.cpp moc_audioinput.cpp moc_config.cpp moc_qaudiolevel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_player.cpp moc_add_music_single.cpp moc_add_full_dir.cpp moc_addgenre.cpp moc_addjingle.cpp moc_add_pub.cpp moc_optionsdialog.cpp moc_aboutus.cpp moc_youtubedownloader.cpp moc_add_program.cpp moc_audioinput.cpp moc_config.cpp moc_qaudiolevel.cpp
moc_player.cpp: player.h \
		phonon/audiooutput.h \
		phonon/phonon_export.h \
		phonon/abstractaudiooutput.h \
		phonon/phonondefs.h \
		phonon/medianode.h \
		phonon/path.h \
		phonon/objectdescription.h \
		phonon/phononnamespace.h \
		phonon/seekslider.h \
		phonon/mediaobject.h \
		phonon/mediasource.h \
		phonon/mrl.h \
		phonon/volumeslider.h \
		phonon/backendcapabilities.h \
		phonon/audiodataoutput.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/fred/cpp/XFB/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/fred/cpp/XFB -I/usr/include/qt -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtDesigner -I/usr/include/qt/QtUiPlugin -I/usr/include/phonon4qt5 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtDataVisualization -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtSql -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/6.2.1 -I/usr/include/c++/6.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include-fixed -I/usr/include -I/usr/include/c++/7.2.0 -I/usr/include/c++/7.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/7.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include-fixed -I/usr/include player.h -o moc_player.cpp

moc_add_music_single.cpp: add_music_single.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/fred/cpp/XFB/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/fred/cpp/XFB -I/usr/include/qt -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtDesigner -I/usr/include/qt/QtUiPlugin -I/usr/include/phonon4qt5 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtDataVisualization -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtSql -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/6.2.1 -I/usr/include/c++/6.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include-fixed -I/usr/include -I/usr/include/c++/7.2.0 -I/usr/include/c++/7.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/7.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include-fixed -I/usr/include add_music_single.h -o moc_add_music_single.cpp

moc_add_full_dir.cpp: add_full_dir.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/fred/cpp/XFB/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/fred/cpp/XFB -I/usr/include/qt -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtDesigner -I/usr/include/qt/QtUiPlugin -I/usr/include/phonon4qt5 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtDataVisualization -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtSql -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/6.2.1 -I/usr/include/c++/6.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include-fixed -I/usr/include -I/usr/include/c++/7.2.0 -I/usr/include/c++/7.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/7.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include-fixed -I/usr/include add_full_dir.h -o moc_add_full_dir.cpp

moc_addgenre.cpp: addgenre.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/fred/cpp/XFB/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/fred/cpp/XFB -I/usr/include/qt -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtDesigner -I/usr/include/qt/QtUiPlugin -I/usr/include/phonon4qt5 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtDataVisualization -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtSql -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/6.2.1 -I/usr/include/c++/6.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include-fixed -I/usr/include -I/usr/include/c++/7.2.0 -I/usr/include/c++/7.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/7.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include-fixed -I/usr/include addgenre.h -o moc_addgenre.cpp

moc_addjingle.cpp: addjingle.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/fred/cpp/XFB/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/fred/cpp/XFB -I/usr/include/qt -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtDesigner -I/usr/include/qt/QtUiPlugin -I/usr/include/phonon4qt5 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtDataVisualization -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtSql -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/6.2.1 -I/usr/include/c++/6.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include-fixed -I/usr/include -I/usr/include/c++/7.2.0 -I/usr/include/c++/7.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/7.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include-fixed -I/usr/include addjingle.h -o moc_addjingle.cpp

moc_add_pub.cpp: add_pub.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/fred/cpp/XFB/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/fred/cpp/XFB -I/usr/include/qt -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtDesigner -I/usr/include/qt/QtUiPlugin -I/usr/include/phonon4qt5 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtDataVisualization -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtSql -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/6.2.1 -I/usr/include/c++/6.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include-fixed -I/usr/include -I/usr/include/c++/7.2.0 -I/usr/include/c++/7.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/7.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include-fixed -I/usr/include add_pub.h -o moc_add_pub.cpp

moc_optionsdialog.cpp: optionsdialog.h \
		player.h \
		phonon/audiooutput.h \
		phonon/phonon_export.h \
		phonon/abstractaudiooutput.h \
		phonon/phonondefs.h \
		phonon/medianode.h \
		phonon/path.h \
		phonon/objectdescription.h \
		phonon/phononnamespace.h \
		phonon/seekslider.h \
		phonon/mediaobject.h \
		phonon/mediasource.h \
		phonon/mrl.h \
		phonon/volumeslider.h \
		phonon/backendcapabilities.h \
		phonon/audiodataoutput.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/fred/cpp/XFB/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/fred/cpp/XFB -I/usr/include/qt -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtDesigner -I/usr/include/qt/QtUiPlugin -I/usr/include/phonon4qt5 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtDataVisualization -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtSql -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/6.2.1 -I/usr/include/c++/6.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include-fixed -I/usr/include -I/usr/include/c++/7.2.0 -I/usr/include/c++/7.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/7.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include-fixed -I/usr/include optionsdialog.h -o moc_optionsdialog.cpp

moc_aboutus.cpp: aboutus.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/fred/cpp/XFB/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/fred/cpp/XFB -I/usr/include/qt -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtDesigner -I/usr/include/qt/QtUiPlugin -I/usr/include/phonon4qt5 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtDataVisualization -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtSql -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/6.2.1 -I/usr/include/c++/6.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include-fixed -I/usr/include -I/usr/include/c++/7.2.0 -I/usr/include/c++/7.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/7.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include-fixed -I/usr/include aboutus.h -o moc_aboutus.cpp

moc_youtubedownloader.cpp: youtubedownloader.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/fred/cpp/XFB/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/fred/cpp/XFB -I/usr/include/qt -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtDesigner -I/usr/include/qt/QtUiPlugin -I/usr/include/phonon4qt5 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtDataVisualization -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtSql -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/6.2.1 -I/usr/include/c++/6.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include-fixed -I/usr/include -I/usr/include/c++/7.2.0 -I/usr/include/c++/7.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/7.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include-fixed -I/usr/include youtubedownloader.h -o moc_youtubedownloader.cpp

moc_add_program.cpp: add_program.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/fred/cpp/XFB/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/fred/cpp/XFB -I/usr/include/qt -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtDesigner -I/usr/include/qt/QtUiPlugin -I/usr/include/phonon4qt5 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtDataVisualization -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtSql -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/6.2.1 -I/usr/include/c++/6.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include-fixed -I/usr/include -I/usr/include/c++/7.2.0 -I/usr/include/c++/7.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/7.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include-fixed -I/usr/include add_program.h -o moc_add_program.cpp

moc_audioinput.cpp: audioinput.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/fred/cpp/XFB/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/fred/cpp/XFB -I/usr/include/qt -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtDesigner -I/usr/include/qt/QtUiPlugin -I/usr/include/phonon4qt5 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtDataVisualization -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtSql -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/6.2.1 -I/usr/include/c++/6.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include-fixed -I/usr/include -I/usr/include/c++/7.2.0 -I/usr/include/c++/7.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/7.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include-fixed -I/usr/include audioinput.h -o moc_audioinput.cpp

moc_config.cpp: config.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/fred/cpp/XFB/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/fred/cpp/XFB -I/usr/include/qt -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtDesigner -I/usr/include/qt/QtUiPlugin -I/usr/include/phonon4qt5 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtDataVisualization -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtSql -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/6.2.1 -I/usr/include/c++/6.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include-fixed -I/usr/include -I/usr/include/c++/7.2.0 -I/usr/include/c++/7.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/7.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include-fixed -I/usr/include config.h -o moc_config.cpp

moc_qaudiolevel.cpp: qaudiolevel.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/fred/cpp/XFB/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/fred/cpp/XFB -I/usr/include/qt -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebKitWidgets -I/usr/include/qt/QtWebKit -I/usr/include/qt/QtDesigner -I/usr/include/qt/QtUiPlugin -I/usr/include/phonon4qt5 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtDataVisualization -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtSql -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/6.2.1 -I/usr/include/c++/6.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include-fixed -I/usr/include -I/usr/include/c++/7.2.0 -I/usr/include/c++/7.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/7.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include-fixed -I/usr/include qaudiolevel.h -o moc_qaudiolevel.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_player.h ui_add_music_single.h ui_add_full_dir.h ui_addgenre.h ui_addjingle.h ui_add_pub.h ui_optionsdialog.h ui_aboutus.h ui_youtubedownloader.h ui_add_program.h
compiler_uic_clean:
	-$(DEL_FILE) ui_player.h ui_add_music_single.h ui_add_full_dir.h ui_addgenre.h ui_addjingle.h ui_add_pub.h ui_optionsdialog.h ui_aboutus.h ui_youtubedownloader.h ui_add_program.h
ui_player.h: player.ui \
		/usr/bin/uic \
		phonon/seekslider.h \
		phonon/volumeslider.h \
		phonon/phonon_export.h \
		phonon/phonondefs.h \
		phonon/phononnamespace.h \
		phonon/phonon_export.h \
		phonon/phonondefs.h
	/usr/bin/uic player.ui -o ui_player.h

ui_add_music_single.h: add_music_single.ui \
		/usr/bin/uic
	/usr/bin/uic add_music_single.ui -o ui_add_music_single.h

ui_add_full_dir.h: add_full_dir.ui \
		/usr/bin/uic
	/usr/bin/uic add_full_dir.ui -o ui_add_full_dir.h

ui_addgenre.h: addgenre.ui \
		/usr/bin/uic
	/usr/bin/uic addgenre.ui -o ui_addgenre.h

ui_addjingle.h: addjingle.ui \
		/usr/bin/uic
	/usr/bin/uic addjingle.ui -o ui_addjingle.h

ui_add_pub.h: add_pub.ui \
		/usr/bin/uic
	/usr/bin/uic add_pub.ui -o ui_add_pub.h

ui_optionsdialog.h: optionsdialog.ui \
		/usr/bin/uic
	/usr/bin/uic optionsdialog.ui -o ui_optionsdialog.h

ui_aboutus.h: aboutus.ui \
		/usr/bin/uic
	/usr/bin/uic aboutus.ui -o ui_aboutus.h

ui_youtubedownloader.h: youtubedownloader.ui \
		/usr/bin/uic
	/usr/bin/uic youtubedownloader.ui -o ui_youtubedownloader.h

ui_add_program.h: add_program.ui \
		/usr/bin/uic
	/usr/bin/uic add_program.ui -o ui_add_program.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

player.o: player.cpp player.h \
		phonon/audiooutput.h \
		phonon/phonon_export.h \
		phonon/abstractaudiooutput.h \
		phonon/phonondefs.h \
		phonon/medianode.h \
		phonon/path.h \
		phonon/objectdescription.h \
		phonon/phononnamespace.h \
		phonon/seekslider.h \
		phonon/mediaobject.h \
		phonon/mediasource.h \
		phonon/mrl.h \
		phonon/volumeslider.h \
		phonon/backendcapabilities.h \
		phonon/audiodataoutput.h \
		ui_player.h \
		add_music_single.h \
		add_full_dir.h \
		addgenre.h \
		addjingle.h \
		add_pub.h \
		add_program.h \
		optionsdialog.h \
		aboutus.h \
		youtubedownloader.h \
		qaudiolevel.h \
		phonon/MediaObject
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o player.cpp

main.o: main.cpp player.h \
		phonon/audiooutput.h \
		phonon/phonon_export.h \
		phonon/abstractaudiooutput.h \
		phonon/phonondefs.h \
		phonon/medianode.h \
		phonon/path.h \
		phonon/objectdescription.h \
		phonon/phononnamespace.h \
		phonon/seekslider.h \
		phonon/mediaobject.h \
		phonon/mediasource.h \
		phonon/mrl.h \
		phonon/volumeslider.h \
		phonon/backendcapabilities.h \
		phonon/audiodataoutput.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

add_music_single.o: add_music_single.cpp add_music_single.h \
		ui_add_music_single.h \
		addgenre.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o add_music_single.o add_music_single.cpp

add_full_dir.o: add_full_dir.cpp add_full_dir.h \
		ui_add_full_dir.h \
		addgenre.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o add_full_dir.o add_full_dir.cpp

addgenre.o: addgenre.cpp addgenre.h \
		ui_addgenre.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addgenre.o addgenre.cpp

addjingle.o: addjingle.cpp addjingle.h \
		ui_addjingle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addjingle.o addjingle.cpp

add_pub.o: add_pub.cpp add_pub.h \
		ui_add_pub.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o add_pub.o add_pub.cpp

optionsdialog.o: optionsdialog.cpp optionsdialog.h \
		player.h \
		phonon/audiooutput.h \
		phonon/phonon_export.h \
		phonon/abstractaudiooutput.h \
		phonon/phonondefs.h \
		phonon/medianode.h \
		phonon/path.h \
		phonon/objectdescription.h \
		phonon/phononnamespace.h \
		phonon/seekslider.h \
		phonon/mediaobject.h \
		phonon/mediasource.h \
		phonon/mrl.h \
		phonon/volumeslider.h \
		phonon/backendcapabilities.h \
		phonon/audiodataoutput.h \
		ui_optionsdialog.h \
		commonFunctions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optionsdialog.o optionsdialog.cpp

aboutus.o: aboutus.cpp aboutus.h \
		ui_aboutus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aboutus.o aboutus.cpp

youtubedownloader.o: youtubedownloader.cpp youtubedownloader.h \
		ui_youtubedownloader.h \
		addgenre.h \
		player.h \
		phonon/audiooutput.h \
		phonon/phonon_export.h \
		phonon/abstractaudiooutput.h \
		phonon/phonondefs.h \
		phonon/medianode.h \
		phonon/path.h \
		phonon/objectdescription.h \
		phonon/phononnamespace.h \
		phonon/seekslider.h \
		phonon/mediaobject.h \
		phonon/mediasource.h \
		phonon/mrl.h \
		phonon/volumeslider.h \
		phonon/backendcapabilities.h \
		phonon/audiodataoutput.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o youtubedownloader.o youtubedownloader.cpp

add_program.o: add_program.cpp add_program.h \
		ui_add_program.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o add_program.o add_program.cpp

audioinput.o: audioinput.cpp audioinput.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o audioinput.o audioinput.cpp

qaudiolevel.o: qaudiolevel.cpp qaudiolevel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qaudiolevel.o qaudiolevel.cpp

qrc_tr.o: qrc_tr.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_tr.o qrc_tr.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_player.o: moc_player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_player.o moc_player.cpp

moc_add_music_single.o: moc_add_music_single.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_add_music_single.o moc_add_music_single.cpp

moc_add_full_dir.o: moc_add_full_dir.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_add_full_dir.o moc_add_full_dir.cpp

moc_addgenre.o: moc_addgenre.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addgenre.o moc_addgenre.cpp

moc_addjingle.o: moc_addjingle.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addjingle.o moc_addjingle.cpp

moc_add_pub.o: moc_add_pub.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_add_pub.o moc_add_pub.cpp

moc_optionsdialog.o: moc_optionsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_optionsdialog.o moc_optionsdialog.cpp

moc_aboutus.o: moc_aboutus.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aboutus.o moc_aboutus.cpp

moc_youtubedownloader.o: moc_youtubedownloader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_youtubedownloader.o moc_youtubedownloader.cpp

moc_add_program.o: moc_add_program.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_add_program.o moc_add_program.cpp

moc_audioinput.o: moc_audioinput.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_audioinput.o moc_audioinput.cpp

moc_config.o: moc_config.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_config.o moc_config.cpp

moc_qaudiolevel.o: moc_qaudiolevel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qaudiolevel.o moc_qaudiolevel.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

